# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies for linters
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.0.0 black==23.1.0
    - name: Lint with flake8
      run: |
        flake8
    - name: Check with black
      run: |
        black --check --line-length 79 .
    - name: Test subways with unittest
      run: |
        export PYTHONPATH=$(pwd)
        pip freeze | xargs pip uninstall -y
        pip install -r subways/requirements.txt
        python -m unittest discover subways
    - name: Test tools with unittest
      run: |
        export PYTHONPATH=$(pwd)
        pip freeze | xargs pip uninstall -y
        pip install -r tools/make_poly/requirements.txt
        python -m unittest discover tools/make_poly
